services:
  attacker:
    build:
      context: ./attacker
      args:
        CVE_FLAG: ${CVE_FLAG:-flag{cloud-17-default}}
    ports:
      - "10617:5000"
    environment:
      - FLAG=${CVE_FLAG:-flag{cloud-17-default}}
      - SVC_A_URL=http://svc-a:5000
  svc-a:
    build: ./svc-a
  svc-b:
    build: ./svc-b
    environment:
      - FLAG2=flag{cloud-17-step2-deputy}
