services:
  model-registry:
    build: ./model-registry
    networks:
      c30-net:
        ipv4_address: 169.254.0.10
  inference:
    build: ./inference
    environment:
      - REGISTRY_URL=http://model-registry:5000
    networks:
      c30-net:
        ipv4_address: 169.254.0.20
  node-imds:
    build: ./node-imds
    environment:
      - ROLE_NAME=eks-node-role
      - ACCESS_KEY=AKIANODEEXAMPLE
      - SECRET_KEY=node-secret-key
      - SESSION_TOKEN=node-session-token
    networks:
      c30-net:
        ipv4_address: 169.254.169.254
  cluster-api:
    build: ./cluster-api
    environment:
      - NODE_TOKEN=node-session-token
      - FLAG=flag{cloud-30-cluster-secrets}
    networks:
      c30-net:
        ipv4_address: 169.254.0.40
  attacker:
    build: ./attacker
    ports:
      - "10630:5000"
    environment:
      - REGISTRY_URL=http://model-registry:5000
      - INFER_URL=http://inference:5000
      - CLUSTER_URL=http://cluster-api:5000
    networks:
      c30-net:
        ipv4_address: 169.254.0.50
networks:
  c30-net:
    driver: bridge
    ipam:
      config:
        - subnet: 169.254.0.0/16
