services:
  control-api:
    build: ./control-api
    environment:
      - FLAG=flag{cloud-20-victim-volume}
    networks:
      c31-net:
        ipv4_address: 10.31.0.10
  attacker-instance:
    build: ./attacker-instance
    environment:
      - API_URL=http://control-api:5000
      - INSTANCE_ID=ocid.instance.9001
    networks:
      c31-net:
        ipv4_address: 10.31.0.20
  attacker:
    build: ./attacker
    ports:
      - "10631:5000"
    environment:
      - API_URL=http://control-api:5000
      - INSTANCE_URL=http://attacker-instance:5000
    networks:
      c31-net:
        ipv4_address: 10.31.0.30
networks:
  c31-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.31.0.0/24
