services:
  sts:
    build: ./sts
    environment:
      - SIGNING_SECRET=shared-signing-secret
    networks:
      c32-net:
        ipv4_address: 10.32.0.10
  directory-api:
    build: ./directory-api
    ports:
      - "10632:5000"
    environment:
      - SIGNING_SECRET=shared-signing-secret
      - FLAG=${CVE_FLAG:-flag{cloud-21-tenant-b-admin}}
    networks:
      c32-net:
        ipv4_address: 10.32.0.20
  attacker:
    profiles: [debug]
    build: ./attacker
    environment:
      - STS_URL=http://sts:5000
      - DIR_URL=http://directory-api:5000
    networks:
      c32-net:
        ipv4_address: 10.32.0.30
networks:
  c32-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.32.0.0/24
